apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django-employee
  name: django-employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-employee
  template:
    metadata:
      labels:
        app: django-employee
    spec:
      containers:
      - image: public.ecr.aws/w1u8s8d4/django
        name: django-employee
        ports:
        - containerPort: 8000
