apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: django-employee
spec:
  selector:
    # Selector for Pods
    app: django-employee
  ports:
    # Port Map
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
